### ISSUE TITLE
Overhaul history pages

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#516]
The issue is an umbrella issue for the following related issues:

- [x] #81 -  changing an alias does not change the last_user_id
- [x] #275 - show entity tagging history
- [x] #515 - entity extension don't appear on history page
- [x] #511 - History pages show up blank
- [x] #472 - combine relationship modifications and basic info modifications
- [x] #275 - Show entity tagging history on entity modifications page
- [ ] #473 - improved UI for field changes
- [ ] #474 - update how os donation and os matches function

**Comment by aepyornis** [comment]
#525 resolves most of these issues.

Two outstanding issues remain:

_#473 - improved UI for field changes_
Field changes were removed from the history page. We can bring them back those in later.

_#474 - update how os donation and os matches function_
Still needs to be done!
