### ISSUE TITLE
Profile Page Improvements Checklist

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#82]
- [x] link font

- [x] references display style

- [x] gray info such as: "Analyst-created lists of people and orgs"

- [x] page alignment

- [x] Begin merging process link

- [x] (past) date 

- [x] hide blurb when empty

- [x] fix blurb spacing
